const level1 = new Level(
    [
        new ChickenSmall(500),
        new Chicken(750),
        new ChickenSmall(840),
        new Chicken(1080),
        new ChickenSmall(1200),
        new Chicken(1300),
    ],
    [
        new Cloud(0),
        new Cloud(400),
        new Cloud(800),
        new Cloud(1200),
        new Cloud(1600),
        new Cloud(2000),
        new Cloud(2400)
    ],
    [
        new Coin(400, 200),
        new Coin(660, 150),
        new Coin(920, 180),
        new Coin(1280, 100),
        new Coin(1540, 220),
    ],
    [
        new Bottle(250),
        new Bottle(650),
        new Bottle(1050),
        new Bottle(250),
        new Bottle(650),
        new Bottle(1050),
        new Bottle(1450),
        new Bottle(1650),
    ],
    [
        new BackgroundObject('img/5_background/layers/air.png', -719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/air.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/air.png', 719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 3),
    ]
);